### ISSUE TITLE
Response 500 on View Detail Article with Wrong URL

### ISSUE THREAD

**Issue by WingerOfOwl** [RecyThing/RecyThing-API#119]
it Must be 404/400
![Screenshot (1680)](https://github.com/RecyThing/RecyThing-API/assets/102946487/6dc5538f-a254-47d5-9816-87d4578044fe)

**Comment by Trois25** [comment]
okay ill fix it

**Comment by WingerOfOwl** [comment]
> okay ill fix it
Ok, Please Text Me if you have done @Trois25

**Comment by Trois25** [comment]
@WingerOfOwl i already fix it, u can check it first dan

**Comment by WingerOfOwl** [comment]
@Trois25 , Still 500 Response
![Screenshot (1694)](https://github.com/RecyThing/RecyThing-API/assets/102946487/2b139d8c-1f76-485f-9a34-6993caa6fe5e)

**Comment by WingerOfOwl** [comment]
ok, done on my post man too, thanks juan
