### ISSUE TITLE
Module Deprecated

### ISSUE THREAD

**Issue by teranixbq** [RecyThing/RecyThing-API#15]
@Exoream @Trois25 
![Screenshot from 2023-11-11 14-04-41](https://github.com/RecyThing/RecyThing-API/assets/66883583/9edc7bab-f548-4079-87e3-a3018a924dd2)

"io/ioutil" is deprecated: As of Go 1.16, ioutil dah ga dipakai dari go version 1.16. Ganti ke `os` jadinya `os.ReadFile`

**Comment by Exoream** [comment]
code sudah saya perbaharui

![Screenshot 2023-11-12 030428](https://github.com/RecyThing/RecyThing-API/assets/133865308/05183a2a-b6fd-4d46-8489-6165a21decc9)
