### ISSUE TITLE
Time stuck

### ISSUE THREAD

**Issue by teranixbq** [RecyThing/RecyThing-API#181]
time pada klaim daily point selalu menampilkan jam utc yang sama.

**preview db**
![Screenshot from 2023-12-10 09-43-47](https://github.com/RecyThing/RecyThing-API/assets/66883583/9fe33fc8-4428-468a-a76c-b07193b35fc6)

**Comment by Trois25** [comment]
kalau itu emang buat nyimpen tanggal hari ini aja buat cek, karena buat daily point gamasuk history pengambilan

**Comment by teranixbq** [comment]
ok noted
