### ISSUE TITLE
Count data for event community not updated

### ISSUE THREAD

**Issue by TaksaWibawa** [RecyThing/RecyThing-API#186]
it should be:
count = {
  count_active
  count_pending
  count_finished
}

![image](https://github.com/RecyThing/RecyThing-API/assets/98959851/f2b1db73-8c01-4b21-a13c-4bf7c75908b2)

![image](https://github.com/RecyThing/RecyThing-API/assets/98959851/c94f39fc-bd8b-4643-92d3-bc8785deaedc)

**Comment by Trois25** [comment]
okay, already fixed
