### ISSUE TITLE
Lower Case enum

### ISSUE THREAD

**Issue by teranixbq** [RecyThing/RecyThing-API#19]
![Screenshot from 2023-11-11 18-48-03](https://github.com/RecyThing/RecyThing-API/assets/66883583/a548ffd0-42cb-4551-94fd-249a13df66e6)

kategori enum pake lower case on `recybot` @tiarajuliarsita

**Comment by tiarajuliarsita** [comment]
difigma bgtu kak pake upper case kaks

**Comment by teranixbq** [comment]
response bodynya jadi ga rapih, biar FE yang handle

**Comment by tiarajuliarsita** [comment]
okai aman
