### ISSUE TITLE
Refactore Login 

### ISSUE THREAD

**Issue by teranixbq** [RecyThing/RecyThing-API#20]
![Screenshot from 2023-11-11 20-54-41](https://github.com/RecyThing/RecyThing-API/assets/66883583/bf16f356-0bb9-4ce0-9df7-4bcdb71cc2c2)

### kode ni saya refactore, dengan alasan berikut : 

- Penamaan variabel dari `CompareHash` jadi `ComparePass`. Karena itu harus menunjukkan apa yang mau di compare
- Tidak ada variabel tambahan , merujuk pada `CompareHash`. Variabel tambahan dapat meningkatkan kejelasan kode dengan memberikan nama yang jelas terhadap hasil perbandingan compare.
- Penanganan Error masih kurang bisa di test, sehingga tidak bisa mengambil error didalam kondisi. error hanya mengambil dari nilai return akhirnya. bukan pada kondisinya
---
### View kode hasil refactore

![Screenshot from 2023-11-11 21-12-37](https://github.com/RecyThing/RecyThing-API/assets/66883583/796efe87-b7bc-4f2a-8f2e-3e541ed789ac)

Changelog : 

- Dengan memindahkan pengecekkan email sudah terverifikasi dari handle ke service.
- Menambahkan spesifikasi variabel dan error di tiap fungsinya.
- Membuat variabel untuk compare pass dengan nama `ComparePass` atau `ComparePassword`

  
***Note** : kode diatas sudah menggunakan validator jadi validasi yang ada sebelumnya sudah di hapus dari fungsi

**Comment by Exoream** [comment]
Saya liat code menjadi lebih efisien dan lebih terstruktur.  Code menjadi lebih mudah di baca dengan tetap mempertahakan fungsional nya
