### ISSUE TITLE
in exchange trash, drop point name should be by the name of drop point in database, not by their address. in view detail it should show name of the drop point

### ISSUE THREAD

**Issue by TaksaWibawa** [RecyThing/RecyThing-API#202]
![image](https://github.com/RecyThing/RecyThing-API/assets/98959851/c4fc99bf-5bd3-41d2-8abe-7d148ae3564d)

**Comment by Exoream** [comment]
done and there is a change in the request json address to drop_point_name. Swagger update soon

![Screenshot 2023-12-12 145324](https://github.com/RecyThing/RecyThing-API/assets/133865308/4c1261ab-0ba0-41c3-a675-86cc119424ae)(url)
