### ISSUE TITLE
Change id reporting

### ISSUE THREAD

**Issue by Exoream** [RecyThing/RecyThing-API#21]
![Screenshot 2023-11-12 030752](https://github.com/RecyThing/RecyThing-API/assets/133865308/1da22eef-61ae-4a57-9a5f-98ccacabb52f)

Bagian id boleh digantikan dengan random generate, soalnya nanti akan ditampilkan di front end nya, jadi keliatan kurang baik.

**Comment by Trois25** [comment]
![image](https://github.com/RecyThing/RecyThing-API/assets/89327360/43150d05-231e-473c-8c4e-1c712ce84e84)

dona mas hilal hehe
