### ISSUE TITLE
Change Enum

### ISSUE THREAD

**Issue by Exoream** [RecyThing/RecyThing-API#22]
Untuk type data enumnya bisa di kecilkan saja hurufnya. Soalnya di tampilan design nya, FE yang atur bukan kita. Jadi di database di kecilin aja hurufnya 
Contohnya "sampah kering", "sampah basah"

![Screenshot 2023-11-12 031751](https://github.com/RecyThing/RecyThing-API/assets/133865308/3a86bbd4-7edb-43ac-aecf-84ae92f76fe3)

UsersId yang jadi foreign key, tambahkan juga gorm foreign key nya.

![Screenshot 2023-11-12 031939](https://github.com/RecyThing/RecyThing-API/assets/133865308/b1931cfb-431b-48f3-8786-ed0a30ea297e)

**Comment by Trois25** [comment]
sampunn, untuk setiap enum diubah ke huruf kecil semua
