### ISSUE TITLE
Response 500 On Join Community

### ISSUE THREAD

**Issue by WingerOfOwl** [RecyThing/RecyThing-API#223]
it Must 404
![Screenshot (1850)](https://github.com/RecyThing/RecyThing-API/assets/102946487/5bae95c3-7aea-4116-b4aa-0642e1a19f0e)

**Comment by Trois25** [comment]
done fixing
![image](https://github.com/RecyThing/RecyThing-API/assets/89327360/48888bc8-f09e-4627-9196-2d967c8a601e)

**Comment by WingerOfOwl** [comment]
@Trois25 thanks mas
