### ISSUE TITLE
Response 200 on View All Event By ID Community

### ISSUE THREAD

**Issue by WingerOfOwl** [RecyThing/RecyThing-API#224]
it must 404
![Screenshot (1852)](https://github.com/RecyThing/RecyThing-API/assets/102946487/c54ff0fd-aaf8-4167-bfac-0be771b92098)

**Comment by Trois25** [comment]
fixed
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDI1Mjk0NTUsImlkIjoiMmE0ZGRlZGYtOGIyNi00YzI2LWEzYmItYjc1ZjcyNTlhYzJmIiwicm9sZSI6IiJ9.zwHoK13j-PxzXEpwiOtTgNN0aOZMHwigtdlbSP3qudc

**Comment by WingerOfOwl** [comment]
@Trois25 thanks mas
