### ISSUE TITLE
Tambahkan kolom keterangan penolakan di tabel reporting

### ISSUE THREAD

**Issue by Exoream** [RecyThing/RecyThing-API#26]
Di dalam model reporting nya ditambahkan kolom alasan penolakan dengan type data desckripsi. Dari tampilan kita butuh itu

![Screenshot 2023-11-13 222135](https://github.com/RecyThing/RecyThing-API/assets/133865308/24a8f3d4-843d-4ef8-b192-678615f3c465)

![Screenshot 2023-11-13 222313](https://github.com/RecyThing/RecyThing-API/assets/133865308/324a18ff-cb40-4849-806c-dcad363be270)

**Comment by Trois25** [comment]
siapp, sudah ditambahkan untuk alasan penolakan dengan variabel RejectionDescription
