### ISSUE TITLE
Bug On Register API [API MOBILE]

### ISSUE THREAD

**Issue by WingerOfOwl** [RecyThing/RecyThing-API#52]
Data Response will Empty if you Register data
![Screenshot (1546)](https://github.com/RecyThing/RecyThing-API/assets/102946487/012611f5-9fdd-47d2-a0f2-cba0a95670f0)

**Comment by teranixbq** [comment]
![Screenshot from 2023-11-19 20-23-17](https://github.com/RecyThing/RecyThing-API/assets/66883583/2e21879c-f30b-4ea3-b154-caef10935aad)

bug find email tidak membutuhkan data melainkan membutuhkan validasi bahwa data itu ada
